# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"UtcTime": "00_core.ipynb",
         "LocalTime": "00_core.ipynb",
         "PosixTime": "00_core.ipynb",
         "MILLIS_IN_A_SECOND": "00_core.ipynb",
         "MICROS_IN_A_MILLI": "00_core.ipynb",
         "seconds_to_millis": "00_core.ipynb",
         "timestamp": "00_core.ipynb",
         "to_utc": "00_core.ipynb",
         "to_local": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://riesfarms.github.io/rtime/"

git_url = "https://github.com/riesfarms/rtime/tree/main/"

def custom_doc_links(name): return None
